# 1. Nombre del Microservicio
spring.application.name=inventario

# 2. Configuración de Conexión a PostgreSQL
# Asegúrate de que el puerto sea 5432 y el nombre de la DB coincida con el que creaste en pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/smartlogix_inventario
spring.datasource.username=postgres
spring.datasource.password=drhiaishna16

# 3. Configuración de JPA / Hibernate
# comprueba que las clases de Java coincidan con las tablas que creamos por SQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. Puerto del Microservicio 
server.port=8081