sonar.projectKey=smartlogix
sonar.projectName=SmartLogix
sonar.sourceEncoding=UTF-8

sonar.sources=Backend/auth/src/main/java,Backend/users/src/main/java,Backend/inventory/src/main/java,Backend/order/src/main/java,Backend/shipping/src/main/java,Backend/notification/src/main/java,Backend/api-gateway/src/main/java,Backend/eureka-server/src/main/java,Frontend/smartlogix-app/src
sonar.tests=Backend/auth/src/test/java,Backend/users/src/test/java,Backend/inventory/src/test/java,Backend/order/src/test/java,Backend/shipping/src/test/java,Backend/notification/src/test/java,Backend/api-gateway/src/test/java,Backend/eureka-server/src/test/java,Frontend/smartlogix-app/src/__tests__

sonar.java.binaries=Backend/auth/target/classes,Backend/users/target/classes,Backend/inventory/target/classes,Backend/order/target/classes,Backend/shipping/target/classes,Backend/notification/target/classes,Backend/api-gateway/target/classes,Backend/eureka-server/target/classes
sonar.coverage.jacoco.xmlReportPaths=Backend/auth/target/site/jacoco/jacoco.xml,Backend/users/target/site/jacoco/jacoco.xml,Backend/inventory/target/site/jacoco/jacoco.xml,Backend/order/target/site/jacoco/jacoco.xml,Backend/shipping/target/site/jacoco/jacoco.xml,Backend/notification/target/site/jacoco/jacoco.xml,Backend/api-gateway/target/site/jacoco/jacoco.xml,Backend/eureka-server/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=Frontend/smartlogix-app/coverage/lcov.info

sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/coverage/**,**/.vite/**,Backend/prisma/generated/**
sonar.test.inclusions=**/*Test.java,**/*.test.ts,**/*.test.tsx
