services:
  # --- Databases ---
  postgres-shipping:
    image: 'postgres:15-alpine'
    container_name: pg-shipping-local
    environment:
      POSTGRES_DB: shipping_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - pg-shipping-data:/var/lib/postgresql/data

  postgres-inventary:
    image: 'postgres:15-alpine'
    container_name: pg-inventary-local
    environment:
      POSTGRES_DB: smartlogix_inventario
      POSTGRES_PASSWORD: drhiaishna16
      POSTGRES_USER: postgres
    ports:
      - '5433:5432'
    volumes:
      - pg-inventary-data:/var/lib/postgresql/data

  postgres-order:
    image: 'postgres:15-alpine'
    container_name: pg-order-local
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5434:5432'
    volumes:
      - pg-order-data:/var/lib/postgresql/data

  postgres-notification:
    image: 'postgres:15-alpine'
    container_name: pg-notification-local
    environment:
      POSTGRES_DB: notificationdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5435:5432'
    volumes:
      - pg-notification-data:/var/lib/postgresql/data

  postgres-auth:
    image: 'postgres:15-alpine'
    container_name: pg-auth-local
    environment:
      POSTGRES_DB: authdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5436:5432'
    volumes:
      - pg-auth-data:/var/lib/postgresql/data

  pg-users-local:
    image: postgres:15-alpine
    container_name: pg-users-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_users
    ports:
      - "5437:5432"
    volumes:
      - pg-users-data:/var/lib/postgresql/data

  # --- Infraestructura ---
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq-local
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server-local
    ports:
      - '8761:8761'
    environment:
      - SERVER_PORT=8761

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-local
    ports:
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - EUREKA_URI=http://eureka-server-local:8761/eureka/
    depends_on:
      - eureka-server

  # --- Microservicios ---
  ms-shipping:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    container_name: ms-shipping-local
    ports:
      - '8084:8084'
    environment:
      - DB_URL=jdbc:postgresql://postgres-shipping:5432/shipping_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - SERVER_PORT=8084
      - EUREKA_URI=http://eureka-server-local:8761/eureka/
    depends_on:
      - postgres-shipping
      - eureka-server

  ms-inventary:
    build:
      context: ./inventary
      dockerfile: Dockerfile
    container_name: ms-inventary-local
    ports:
      - '8081:8081'
    environment:
      - DB_URL=jdbc:postgresql://postgres-inventary:5432/smartlogix_inventario
      - DB_USERNAME=postgres
      - DB_PASSWORD=drhiaishna16
      - SERVER_PORT=8081
      - EUREKA_URI=http://eureka-server-local:8761/eureka/
    depends_on:
      - postgres-inventary
      - eureka-server

  ms-order:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: ms-order-local
    ports:
      - '8082:8082'
    environment:
      - DB_URL=jdbc:postgresql://postgres-order:5432/orderdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=8082
      - EUREKA_URI=http://eureka-server-local:8761/eureka/
    depends_on:
      - postgres-order
      - ms-notification
      - eureka-server

  ms-notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: ms-notification-local
    ports:
      - '8085:8085'
    environment:
      - DB_URL=jdbc:postgresql://postgres-notification:5432/notificationdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=8085
      - EUREKA_URI=http://eureka-server-local:8761/eureka/
    depends_on:
      - postgres-notification
      - eureka-server

  ms-users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: ms-users-local
    restart: unless-stopped
    ports:
      - "8083:8083"
    env_file:
      - ./users/.env
    depends_on:
      - pg-users-local
      - eureka-server


  ms-auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: ms-auth-local
    ports:
      - '8086:8086'
    environment:
      - DB_URL=jdbc:postgresql://postgres-auth:5432/authdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=8086
      - JWT_SECRET=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c2d6395af
      - JWT_EXPIRATION=86400000
      - EUREKA_URI=http://eureka-server-local:8761/eureka/
    depends_on:
      - postgres-auth
      - eureka-server

volumes:
  pg-shipping-data:
  pg-inventary-data:
  pg-order-data:
  pg-notification-data:
  pg-auth-data:
  pg-users-data:
  rabbitmq-data:
