# Clave secreta para firmar los JWT (Usa una cadena larga y aleatoria)
# En producción, esto debería venir de una variable de entorno
smartlogix.auth.jwt-secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c2d6395af
# El token expirará en 24 horas (86400000 ms)
smartlogix.auth.jwt-expiration=86400000