server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/smartlogix/auth/**
        - id: ms-inventary
          uri: lb://ms-inventary
          predicates:
            - Path=/smartlogix/inventary/**
        - id: ms-order
          uri: lb://ms-order
          predicates:
            - Path=/smartlogix/order/**
        - id: ms-shipping
          uri: lb://ms-shipping
          predicates:
            - Path=/smartlogix/shipping/**
        - id: ms-notification
          uri: lb://ms-notification
          predicates:
            - Path=/smartlogix/notification/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
