server:
  port: ${SERVER_PORT:8082}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ms-order
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orderdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Esta propiedad se eliminará en la Fase 3 cuando usemos Feign + Eureka
notification:
  service:
    url: ${NOTIFICATION_URL:http://localhost:8085}

eureka:
  client:
    enabled: false # Se habilitará en la Fase 3
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}