-- Datos geográficos de Chile (fuente: SINIM / Decreto Exento N° 817, 2010)
-- Idempotente: ON CONFLICT DO NOTHING — seguro en cualquier arranque del contenedor

INSERT INTO pais(id, nombre) VALUES (1, 'Chile') ON CONFLICT DO NOTHING;

-- Regiones
INSERT INTO region(id, nombre, pais_id) VALUES (1,  'Tarapacá', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (2,  'Antofagasta', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (3,  'Atacama', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (4,  'Coquimbo', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (5,  'Valparaíso', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (6,  'Región del Libertador Gral. Bernardo O''Higgins', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (7,  'Región del Maule', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (8,  'Región del Biobío', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (9,  'Región de la Araucanía', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (10, 'Región de Los Lagos', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (11, 'Región Aisén del Gral. Carlos Ibáñez del Campo', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (12, 'Región de Magallanes y de la Antártica Chilena', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (13, 'Región Metropolitana de Santiago', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (14, 'Región de Los Ríos', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (15, 'Arica y Parinacota', 1) ON CONFLICT DO NOTHING;
INSERT INTO region(id, nombre, pais_id) VALUES (16, 'Región de Ñuble', 1) ON CONFLICT DO NOTHING;

-- Comunas Región 1 - Tarapacá
INSERT INTO comuna(id, nombre, region_id) VALUES (1101, 'Iquique', 1) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (1107, 'Alto Hospicio', 1) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (1401, 'Pozo Almonte', 1) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (1402, 'Camiña', 1) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (1403, 'Colchane', 1) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (1404, 'Huara', 1) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (1405, 'Pica', 1) ON CONFLICT DO NOTHING;

-- Comunas Región 2 - Antofagasta
INSERT INTO comuna(id, nombre, region_id) VALUES (2101, 'Antofagasta', 2) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (2102, 'Mejillones', 2) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (2103, 'Sierra Gorda', 2) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (2104, 'Taltal', 2) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (2201, 'Calama', 2) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (2202, 'Ollagüe', 2) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (2203, 'San Pedro de Atacama', 2) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (2301, 'Tocopilla', 2) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (2302, 'María Elena', 2) ON CONFLICT DO NOTHING;

-- Comunas Región 3 - Atacama
INSERT INTO comuna(id, nombre, region_id) VALUES (3101, 'Copiapó', 3) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (3102, 'Caldera', 3) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (3103, 'Tierra Amarilla', 3) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (3201, 'Chañaral', 3) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (3202, 'Diego de Almagro', 3) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (3301, 'Vallenar', 3) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (3302, 'Alto del Carmen', 3) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (3303, 'Freirina', 3) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (3304, 'Huasco', 3) ON CONFLICT DO NOTHING;

-- Comunas Región 4 - Coquimbo
INSERT INTO comuna(id, nombre, region_id) VALUES (4101, 'La Serena', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4102, 'Coquimbo', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4103, 'Andacollo', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4104, 'La Higuera', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4105, 'Paihuano', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4106, 'Vicuña', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4201, 'Illapel', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4202, 'Canela', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4203, 'Los Vilos', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4204, 'Salamanca', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4301, 'Ovalle', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4302, 'Combarbalá', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4303, 'Monte Patria', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4304, 'Punitaqui', 4) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (4305, 'Río Hurtado', 4) ON CONFLICT DO NOTHING;

-- Comunas Región 5 - Valparaíso
INSERT INTO comuna(id, nombre, region_id) VALUES (5101, 'Valparaíso', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5102, 'Casablanca', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5103, 'Concón', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5104, 'Juan Fernández', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5105, 'Puchuncaví', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5107, 'Quintero', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5109, 'Viña del Mar', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5201, 'Isla de Pascua', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5301, 'Los Andes', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5302, 'Calle Larga', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5303, 'Rinconada', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5304, 'San Esteban', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5401, 'La Ligua', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5402, 'Cabildo', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5403, 'Papudo', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5404, 'Petorca', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5405, 'Zapallar', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5501, 'Quillota', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5502, 'La Calera', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5503, 'Hijuelas', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5504, 'La Cruz', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5506, 'Nogales', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5601, 'San Antonio', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5602, 'Algarrobo', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5603, 'Cartagena', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5604, 'El Quisco', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5605, 'El Tabo', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5606, 'Santo Domingo', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5701, 'San Felipe', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5702, 'Catemu', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5703, 'Llay Llay', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5704, 'Panquehue', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5705, 'Putaendo', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5706, 'Santa María', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5801, 'Quilpué', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5802, 'Limache', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5803, 'Olmué', 5) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (5804, 'Villa Alemana', 5) ON CONFLICT DO NOTHING;

-- Comunas Región 6 - O'Higgins
INSERT INTO comuna(id, nombre, region_id) VALUES (6101, 'Rancagua', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6102, 'Codegua', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6103, 'Coinco', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6104, 'Coltauco', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6105, 'Doñihue', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6106, 'Graneros', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6107, 'Las Cabras', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6108, 'Machalí', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6109, 'Malloa', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6110, 'Mostazal', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6111, 'Olivar', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6112, 'Peumo', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6113, 'Pichidegua', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6114, 'Quinta de Tilcoco', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6115, 'Rengo', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6116, 'Requínoa', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6117, 'San Vicente', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6201, 'Pichilemu', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6202, 'La Estrella', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6203, 'Litueche', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6204, 'Marchihue', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6205, 'Navidad', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6206, 'Paredones', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6301, 'San Fernando', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6302, 'Chépica', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6303, 'Chimbarongo', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6304, 'Lolol', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6305, 'Nancagua', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6306, 'Palmilla', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6307, 'Peralillo', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6308, 'Placilla', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6309, 'Pumanque', 6) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (6310, 'Santa Cruz', 6) ON CONFLICT DO NOTHING;

-- Comunas Región 7 - Maule
INSERT INTO comuna(id, nombre, region_id) VALUES (7101, 'Talca', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7102, 'Constitución', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7103, 'Curepto', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7104, 'Empedrado', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7105, 'Maule', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7106, 'Pelarco', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7107, 'Pencahue', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7108, 'Río Claro', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7109, 'San Clemente', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7110, 'San Rafael', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7201, 'Cauquenes', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7202, 'Chanco', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7203, 'Pelluhue', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7301, 'Curicó', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7302, 'Hualañé', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7303, 'Licantén', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7304, 'Molina', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7305, 'Rauco', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7306, 'Romeral', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7307, 'Sagrada Familia', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7308, 'Teno', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7309, 'Vichuquén', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7401, 'Linares', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7402, 'Colbún', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7403, 'Longaví', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7404, 'Parral', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7405, 'Retiro', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7406, 'San Javier', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7407, 'Villa Alegre', 7) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (7408, 'Yerbas Buenas', 7) ON CONFLICT DO NOTHING;

-- Comunas Región 8 - Biobío
INSERT INTO comuna(id, nombre, region_id) VALUES (8101, 'Concepción', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8102, 'Coronel', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8103, 'Chiguayante', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8104, 'Florida', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8105, 'Hualqui', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8106, 'Lota', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8107, 'Penco', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8108, 'San Pedro de la Paz', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8109, 'Santa Juana', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8110, 'Talcahuano', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8111, 'Tomé', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8112, 'Hualpén', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8201, 'Lebu', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8202, 'Arauco', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8203, 'Cañete', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8204, 'Contulmo', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8205, 'Curanilahue', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8206, 'Los Álamos', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8207, 'Tirúa', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8301, 'Los Ángeles', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8302, 'Antuco', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8303, 'Cabrero', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8304, 'Laja', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8305, 'Mulchén', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8306, 'Nacimiento', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8307, 'Negrete', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8308, 'Quilaco', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8309, 'Quilleco', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8310, 'San Rosendo', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8311, 'Santa Bárbara', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8312, 'Tucapel', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8313, 'Yumbel', 8) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8314, 'Alto Biobío', 8) ON CONFLICT DO NOTHING;

-- Comunas Región 9 - Araucanía
INSERT INTO comuna(id, nombre, region_id) VALUES (9101, 'Temuco', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9102, 'Carahue', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9103, 'Cunco', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9104, 'Curarrehue', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9105, 'Freire', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9106, 'Galvarino', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9107, 'Gorbea', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9108, 'Lautaro', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9109, 'Loncoche', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9110, 'Melipeuco', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9111, 'Nueva Imperial', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9112, 'Padre las Casas', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9113, 'Perquenco', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9114, 'Pitrufquén', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9115, 'Pucón', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9116, 'Saavedra', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9117, 'Teodoro Schmidt', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9118, 'Toltén', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9119, 'Vilcún', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9120, 'Villarrica', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9121, 'Cholchol', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9201, 'Angol', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9202, 'Collipulli', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9203, 'Curacautín', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9204, 'Ercilla', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9205, 'Lonquimay', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9206, 'Los Sauces', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9207, 'Lumaco', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9208, 'Purén', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9209, 'Renaico', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9210, 'Traiguén', 9) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (9211, 'Victoria', 9) ON CONFLICT DO NOTHING;

-- Comunas Región 10 - Los Lagos
INSERT INTO comuna(id, nombre, region_id) VALUES (10101, 'Puerto Montt', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10102, 'Calbuco', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10103, 'Cochamó', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10104, 'Fresia', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10105, 'Frutillar', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10106, 'Los Muermos', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10107, 'Llanquihue', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10108, 'Maullín', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10109, 'Puerto Varas', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10201, 'Castro', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10202, 'Ancud', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10203, 'Chonchi', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10204, 'Curaco de Vélez', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10205, 'Dalcahue', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10206, 'Puqueldón', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10207, 'Queilén', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10208, 'Quellón', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10209, 'Quemchi', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10210, 'Quinchao', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10301, 'Osorno', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10302, 'Puerto Octay', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10303, 'Purranque', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10304, 'Puyehue', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10305, 'Río Negro', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10306, 'San Juan de la Costa', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10307, 'San Pablo', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10401, 'Chaitén', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10402, 'Futaleufú', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10403, 'Hualaihué', 10) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (10404, 'Palena', 10) ON CONFLICT DO NOTHING;

-- Comunas Región 11 - Aysén
INSERT INTO comuna(id, nombre, region_id) VALUES (11101, 'Coyhaique', 11) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (11102, 'Lago Verde', 11) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (11201, 'Aysén', 11) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (11202, 'Cisnes', 11) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (11203, 'Guaitecas', 11) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (11301, 'Cochrane', 11) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (11302, 'O''Higgins', 11) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (11303, 'Tortel', 11) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (11401, 'Chile Chico', 11) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (11402, 'Río Ibáñez', 11) ON CONFLICT DO NOTHING;

-- Comunas Región 12 - Magallanes
INSERT INTO comuna(id, nombre, region_id) VALUES (12101, 'Punta Arenas', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12102, 'Laguna Blanca', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12103, 'Río Verde', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12104, 'San Gregorio', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12201, 'Cabo de Hornos', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12202, 'Antártica', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12301, 'Porvenir', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12302, 'Primavera', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12303, 'Timaukel', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12401, 'Natales', 12) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (12402, 'Torres del Paine', 12) ON CONFLICT DO NOTHING;

-- Comunas Región 13 - Metropolitana
INSERT INTO comuna(id, nombre, region_id) VALUES (13101, 'Santiago', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13102, 'Cerrillos', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13103, 'Cerro Navia', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13104, 'Conchalí', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13105, 'El Bosque', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13106, 'Estación Central', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13107, 'Huechuraba', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13108, 'Independencia', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13109, 'La Cisterna', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13110, 'La Florida', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13111, 'La Granja', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13112, 'La Pintana', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13113, 'La Reina', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13114, 'Las Condes', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13115, 'Lo Barnechea', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13116, 'Lo Espejo', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13117, 'Lo Prado', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13118, 'Macul', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13119, 'Maipú', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13120, 'Ñuñoa', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13121, 'Pedro Aguirre Cerda', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13122, 'Peñalolén', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13123, 'Providencia', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13124, 'Pudahuel', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13125, 'Quilicura', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13126, 'Quinta Normal', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13127, 'Recoleta', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13128, 'Renca', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13129, 'San Joaquín', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13130, 'San Miguel', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13131, 'San Ramón', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13132, 'Vitacura', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13201, 'Puente Alto', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13202, 'Pirque', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13203, 'San José de Maipo', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13301, 'Colina', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13302, 'Lampa', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13303, 'Tiltil', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13401, 'San Bernardo', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13402, 'Buin', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13403, 'Calera de Tango', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13404, 'Paine', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13501, 'Melipilla', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13502, 'Alhué', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13503, 'Curacaví', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13504, 'María Pinto', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13505, 'San Pedro', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13601, 'Talagante', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13602, 'El Monte', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13603, 'Isla de Maipo', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13604, 'Padre Hurtado', 13) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (13605, 'Peñaflor', 13) ON CONFLICT DO NOTHING;

-- Comunas Región 14 - Los Ríos
INSERT INTO comuna(id, nombre, region_id) VALUES (14101, 'Valdivia', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14102, 'Corral', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14103, 'Lanco', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14104, 'Los Lagos', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14105, 'Máfil', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14106, 'Mariquina', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14107, 'Paillaco', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14108, 'Panguipulli', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14201, 'La Unión', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14202, 'Futrono', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14203, 'Lago Ranco', 14) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (14204, 'Río Bueno', 14) ON CONFLICT DO NOTHING;

-- Comunas Región 15 - Arica y Parinacota
INSERT INTO comuna(id, nombre, region_id) VALUES (15101, 'Arica', 15) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (15102, 'Camarones', 15) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (15201, 'Putre', 15) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (15202, 'General Lagos', 15) ON CONFLICT DO NOTHING;

-- Comunas Región 16 - Ñuble
INSERT INTO comuna(id, nombre, region_id) VALUES (8401, 'Chillán', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8402, 'Bulnes', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8403, 'Cobquecura', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8404, 'Coelemu', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8405, 'Coihueco', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8406, 'Chillán Viejo', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8407, 'El Carmen', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8408, 'Ninhue', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8409, 'Ñiquén', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8410, 'Pemuco', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8411, 'Pinto', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8412, 'Portezuelo', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8413, 'Quillón', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8414, 'Quirihue', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8415, 'Ránquil', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8416, 'San Carlos', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8417, 'San Fabián', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8418, 'San Ignacio', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8419, 'San Nicolás', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8420, 'Treguaco', 16) ON CONFLICT DO NOTHING;
INSERT INTO comuna(id, nombre, region_id) VALUES (8421, 'Yungay', 16) ON CONFLICT DO NOTHING;
